### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by vabene1111** [ultrabug/mkdocs-static-i18n#145]
Hi, thanks for this awesome project. I probably just have some configuration wrong but i am getting an error in the nav translation generation

```
  File "f:\developement\django\recipes\venv\lib\site-packages\mkdocs\plugins.py", line 514, in run_event
    result = method(item, **kwargs)
  File "f:\developement\django\recipes\venv\lib\site-packages\mkdocs_static_i18n\plugin.py", line 392, in on_nav
    nav = folder_structure.on_nav(self, nav, config, files)
  File "f:\developement\django\recipes\venv\lib\site-packages\mkdocs_static_i18n\folder_structure.py", line 345, in on_nav
    for item in self.i18n_navs[language]:
  File "f:\developement\django\recipes\venv\lib\site-packages\mkdocs\structure\nav.py", line 39, in __iter__
    return iter(self.items)
TypeError: 'NoneType' object is not iterable

```

this is my mkdocs.yml
```yml
site_name: Tandoor Recipes
site_description: Tandoor Recipes Documentation
site_author: vabene1111
repo_url: https://github.com/TandoorRecipes/recipes
edit_uri: https://github.com/TandoorRecipes/recipes/tree/develop/docs
extra_css:
  - stylesheets/extra.css

theme:
  name: material
  repo: fontawesome/brands/github
  logo: logo_color.svg
  favicon: logo_color.svg
  palette:
    scheme: slate

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences

plugins:
  - include-markdown
  - i18n:
      default_language: en
      material_alternate: true
      docs_structure: folder
      languages:
        en:
          name: English
        de:
          name: Deutsch

nav:
  - Home: 'index.md'
  - Installation:
      - Docker: install/docker.md
      - Unraid: install/unraid.md
      - Synology: install/synology.md
      - Kubernetes: install/kubernetes.md
      - KubeSail or PiBox: install/kubesail.md
      - Manual: install/manual.md
      - Homeassistant: install/homeassistant.md
      - Other setups: install/other.md
  - Features:
      - Templating: features/templating.md
      - Shopping: features/shopping.md
      - Authentication: features/authentication.md
      - Storages and Sync: features/external_recipes.md
      - Import/Export: features/import_export.md
  - System:
      - Updating: system/updating.md
      - Permission System: system/permissions.md
      - Backup: system/backup.md
  - Contributing: contribute.md
  - FAQ: faq.md

```

and this is the folder structure I am trying

![image](https://user-images.githubusercontent.com/6819595/193908645-4510b8b6-e732-46fa-8705-b849f7427ebb.png)

basically trying to install your plugin into https://github.com/TandoorRecipes/recipes

thanks in advance for any help!
