### ISSUE TITLE
Having issue with OpenAPI localization

### ISSUE THREAD

**Issue by koshelekapi** [ultrabug/mkdocs-static-i18n#146]
Hello!

I don't know is that really an issue, but I've faced such an effect.

I have a documentation portal in two languages. Source files are located into related folders (`docs/en/...` and `docs/ru/...`).
We enabled the i18n plugin, and in general, it works fine. But: we also have API documentation in YAML format. It is presented in two languages located in related folders, too.
And when we open the page containing such a API specification and switch the language, it doesn't render.
Steps to reproduce:
1. Visit http://shahid.ru/cm_loyalty_online_api/api_requests/
2. See the correct API specification
3. Change the language to English using the language selector on the top
4. See the error "Fetch errorNot Found loyalty_api.yaml"
But I can guarantee that this file exists( All necessary files are included to the `nav` section of the `mkdocs.yml` file. What can be the problem?

My `mkdocs.yml` configuration section:

```
# Plugins
plugins:
  - search
  - include-markdown
  - render_swagger
  - build_plantuml:
      render: 'server' # or "local" for local rendering
      bin_path: '/usr/local/bin/plantuml' # ignored when render: server
      server: 'http://www.plantuml.com/plantuml' # offical plantuml server
      disable_ssl_certificate_validation: true # for self-signed and invalid certs
      output_format: 'png' # or "png"
#     diagram_root: 'docs/diagrams' # should reside under docs_dir
      output_folder: 'out'
      input_folder: 'src'
      input_extensions: '' # comma separated list of extensions to parse, by default every file is parsed
  - i18n:
      default_language: ru
      default_language_only: false
      material_alternate: true
      docs_structure: folder
      languages:
        ru:
          name: Русский
          link: /ru
        en: 
          name: English
          link: /en
```
