### ISSUE TITLE
Is there any way to support cookie consent translation

### ISSUE THREAD

**Issue by icebilly** [ultrabug/mkdocs-static-i18n#191]
hi, we use materia for mkdocs, use google analytics as well, it seems the mkdocs-static-i18n plugin not support translation these content yet.
![image](https://user-images.githubusercontent.com/21252620/219613251-9b4a65d7-4a48-4ffc-80e3-fc9fe6d71848.png)

**Comment by ultrabug** [comment]
Hi @icebilly 

My first impression here is that this plugin can't be expected to support the translation of every theme/plugin out there but since we're talking about mkdocs-material specifically and that I know that Martin cares, I'd like to kindly ask him his take on this.

@squidfunk Hello, do you have plans or don't you think that this kind of translations should fall into mkdocs-material's own localization support please?

**Comment by squidfunk** [comment]
The [cookie consent](https://squidfunk.github.io/mkdocs-material/setup/ensuring-data-privacy/#cookie-consent) is already fully localizable.

---

The [`title`](https://squidfunk.github.io/mkdocs-material/setup/ensuring-data-privacy/#+consent.title) and [`description`](https://squidfunk.github.io/mkdocs-material/setup/ensuring-data-privacy/#+consent.description) (= body) of the cookie consent can be set via `mkdocs.yml`:

``` yaml
extra:
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
```

The [`cookies`](https://squidfunk.github.io/mkdocs-material/setup/ensuring-data-privacy/#+consent.cookies) themselves can also be changed/translated:

``` yaml
extra:
  consent:
    cookies:
      analytics: Custom name
```

The buttons are localized via our regular translation system, e.g. for [French](https://github.com/squidfunk/mkdocs-material/blob/master/src/partials/languages/fr.html):

```
  ...
  "consent.accept": "Accepter",
  "consent.manage": "Paramétrer vos choix",
  "consent.reject": "Refuser",
  ...
```

All parts of Material for MkDocs are localizable. I'm not sure how the localization approach that is implemented in this plugin must be adjusted, but if you build separate sites and link them with the language selector, everything works out-of-the-box (without using this plugin). I understand that this plugin offers some niceties that make localization simpler, but I haven't used it, so I can't really say what would be necessary to add support here.
