### ISSUE TITLE
Incompatible with mkdocs-material privacy plugin

### ISSUE THREAD

**Issue by jonaharagon** [ultrabug/mkdocs-static-i18n#196]
https://squidfunk.github.io/mkdocs-material/setup/ensuring-data-privacy/#built-in-privacy-plugin

The privacy plugin is supposed to automatically download `mermaid.min.js` and replace 
```https://unpkg.com/mermaid@9.3.0/dist/mermaid.min.js```
 in [`bundle.ce72ebac.min.js`](https://github.com/squidfunk/mkdocs-material/blob/master/material/assets/javascripts/bundle.ce72ebac.min.js) with 
```https://<my domain>/assets/external/unpkg.com/mermaid@9.3.0/dist/mermaid.min.js```.

This works fine with a standard mkdocs-material install, but after enabling the i18n plugin this no longer works. The `mermaid.min.js` file gets downloaded, but the URL in the theme's JS file no longer gets updated by the privacy plugin, so it still makes a connection to the external CDN.

---

I can recreate this issue with the following minimal config:

`mkdocs.yml`:

```
site_name: My Docs
theme:
  name: material

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - privacy
  - i18n:
      default_language: en
      languages:
        en:
          name: English
```

`docs/index.en.md`:

````
# Mermaid Diagram

``` mermaid
graph TB
    Start[Start] --> anonymous{Trying to be<br> anonymous?}
    anonymous--> | Yes | tor(Use Tor)
    anonymous --> | No | censorship{Avoiding<br> censorship?}
    censorship --> | Yes | vpnOrTor(Use<br> VPN or Tor)
    censorship --> | No | privacy{Want privacy<br> from ISP?}
    privacy --> | Yes | vpnOrTor
    privacy --> | No | obnoxious{ISP makes<br> obnoxious<br> redirects?}
    obnoxious --> | Yes | encryptedDNS(Use<br> encrypted DNS<br> with 3rd party)
    obnoxious --> | No | ispDNS{Does ISP support<br> encrypted DNS?}
    ispDNS --> | Yes | useISP(Use<br> encrypted DNS<br> with ISP)
    ispDNS --> | No | nothing(Do nothing)
```
````
