### ISSUE TITLE
Config value 'plugins': Plugin 'i18n' option 'languages': Expected a list of items, but a <class 'dict'> was given.

### ISSUE THREAD

**Issue by Chen-Luan** [ultrabug/mkdocs-static-i18n#250]
Two months ago, I successfully deployed a webpage on GitHub Pages using this plugin. Today, when I modified the webpage, Action reported an error.
My webpage can be deployed and browsed locally, but it cannot be deployed to GitHub Pages.

GitHub Actions:
```
Run mkdocs gh-deploy --force
mkdocs gh-deploy --force
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/[3](https://github.com/Chen-Luan/Knowledge_Sharing_Library/actions/runs/6050283095/job/16419272709#step:7:3).11.[4](https://github.com/Chen-Luan/Knowledge_Sharing_Library/actions/runs/6050283095/job/16419272709#step:7:4)/x64
    PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.11.4/x64/lib/pkgconfig
    Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.11.4/x64
    Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.11.4/x64
    Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.11.4/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.11.4/x64/lib
    cache_id: 3[5](https://github.com/Chen-Luan/Knowledge_Sharing_Library/actions/runs/6050283095/job/16419272709#step:7:5)
  
ERROR   -  Config value 'plugins': Plugin 'i1[8](https://github.com/Chen-Luan/Knowledge_Sharing_Library/actions/runs/6050283095/job/16419272709#step:7:8)n' option 'languages': Expected a list of items, but a <class 'dict'> was given.

Aborted with 1 configuration errors!
Error: Process completed with exit code 1.
```

ci.yml:
```
name: ci 
on:
  push:
    branches:
      - master 
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install \
          mkdocs-material \
          mkdocs-static-i18n \
          mkdocs-git-revision-date-localized-plugin
      - run: mkdocs gh-deploy --force
```
