### ISSUE TITLE
Multiple regressions in 1.0.2

### ISSUE THREAD

**Issue by kamilkrzyskow** [ultrabug/mkdocs-static-i18n#251]
The regressions might have been present in version 1.0.0, but I haven't verified it. I simply used the latest available version. Some of these issues could be intentional (though I hope not). Please consider this a mega-thread of challenges I faced while migrating to the newer version. 😃

Environment: 
- Windows 10
- Python 3.11.3
- [pip freeze.txt](https://github.com/ultrabug/mkdocs-static-i18n/files/12502018/pip.freeze.txt)

<details>
<summary>i18n 1.0.2 plugin config</summary>

```yml
  - i18n:
      docs_structure: suffix
      languages:
        - name: en - English
          locale: en
          default: true
          build: true
          nav_translations:
            Afsp: AFSP
            Anims: Animations
            Contribute: How To Contribute
            Daedalus tools: Daedalus
            General info: General information
            Genome: Genome (G3/R1)
            Lego: LeGo
            Vdfs tools: VDFS
            Zengin: ZenGin (G1/G2)
            Zgamepad: zGamePad
            Zparserextender: zParserExtender
        - name: pl - Polski
          locale: pl
          default: false
          build: !ENV [GMC_ENABLE_ON_PUBLISH, True]
          site_description: 'Gothic Modding Community to zbiór pomocnych materiałów do modowania gier Gothic i Risen.'
          nav_translations:
            Anims: Animacje
            Applications: Zastosowania
            Classes: Klasy
            Contribute: Jak Się Udzielić
            Examples: Przykłady
            Extenders: Extendery
            Extensions: Rozszerzenia
            Functions: Funkcje
            General info: Informacje ogólne
            Home: Strona Główna
            Plugins: Wtyczki
            Scripts: Skrypty
            Sound: Dźwięk
            Standalone: Samodzielne
            Syntax extensions: Rozszerzenia składni
            Tools: Narzędzia
            Tutorials: Poradniki
            Various: Różne
            Worlds: Światy
        - name: cs - Čeština
          locale: cs
          default: false
          build: !ENV [GMC_ENABLE_ON_PUBLISH, True]
          site_description: 'Dokumentace, návody a články zaměřené na modování her Gothic a Risen.'
```

</details>

<details>
<summary>File structure</summary>

https://tree.nathanfriend.io/
```
.
├── docs/
│   ├── some_dir/
│   │   └── some_more_dirs
│   ├── index.md # Default language AND fallback
│   ├── index.pl.md # Polish language
│   └── index.cs.md # Czech language
├── overrides/
│   ├── assets/
│   │   ├── images/
│   │   ├── javascript/
│   │   └── stylesheets/
│   └── main.html
└── mkdocs.yml
```

</details>

---

Issues:

1. Relative Path Warnings:
    When building subsequent languages, warnings appear for relative paths to the overrides directory (no issues for the default language).
    ```
    INFO    -  mkdocs_static_i18n: Translated 23 navigation elements to 'pl'
    WARNING -  Doc file 'zengin/scripts/classes/c_info.md' contains a relative link
           '../../../assets/images/c_info_description.png', but the target
           'assets/images/c_info_description.png' is not found among
           documentation files.
    ```
    There's only a default language version of the file, and when the Polish version falls back to it, the path doesn't match. This warning wasn't present in plugin version 0.5.6* with MkDocs 1.5.2, although the error was partially there. With my MkDocs configuration using directory paths, the path gets altered with an additional `../` for the default language. In version 0.5.6, the paths in other languages were consistent with the default language. However, in version 1.0.2, they remain as is in the Markdown.

2. Global Parameters:
    The previous `default_language` and `default_language_only` parameters were handy for CI and making swift local development changes using environment variables (`GMC_DEFAULT_LANG`, `GMC_ONLY_DEFAULT_LANG`). The new config seems to have reversed the behavior, making the default language obligatory. I might be able to work with that, but the subsequent issue is more concerning.

3. Language Toggling Issues:
    Given that each language now has an individual toggle for `default`, it's not feasible to set a single environment variable. In addition, swapping the values temporarily (e.g., en <-> pl) is currently not possible due to the existing file structure:
    ```
    Exception: Conflicting files for the default language 'pl': choose either 'index.pl.md' or 'index.md' but not both
    ```
    The latest version seems to connect `default` with `fallback`. This results in a conflict when I aim to use `index.pl.md` as the default, while intending `index.md` to act as a fallback for the English version. I certainly don't intend to alter the file structure to accommodate files like `index.en.md`.

4. Build Time Logs:
    The output displays individual build times for each build rather than a single cumulative log at the end.
    ```
    INFO    -  Documentation built in 8.28 seconds
    INFO    -  Documentation built in 35.00 seconds
    ```
    I recall somewhat resolving this to show only the final time log, but maybe MkDocs 1.5 altered the way duplicate filters operate.

These are my primary concerns for now. I'll update this list as I progress further.

---

*Note: While I did use a modified variant of plugin version 0.5.6, to the best of my recollection, none of the regressions mentioned were connected to those modifications. [See modifications here](https://github.com/kamilkrzyskow/i18n/commits/i18n-gmc).
