### ISSUE TITLE
Unclear how to work with mkdocs-static-i18n and mike versioning at the same time

### ISSUE THREAD

**Issue by jodygarnett** [ultrabug/mkdocs-static-i18n#265]
Really enjoying this project, running into a difficulty combing ``mike`` publishing and `mkdocs-static-i18n` language control.

I am sure I just do not understand the interaction between these two plugins.

From the "home" page the language chooser is ending up directing to 404 page:

1. From here https://jodygarnett.github.io/core-geonetwork/4.2.5/ selecting `fr` 404: https://jodygarnett.github.io/fr/

2. From https://jodygarnett.github.io/core-geonetwork/4.2.5/fr/ selecting `en` 200 (but empty): https://jodygarnett.github.io

3. From https://jodygarnett.github.io/core-geonetwork/4.2.5/devel/docs/markdown/ selecting `fr` 200: https://jodygarnett.github.io/core-geonetwork/4.2.5/fr/devel/docs/markdown/

My `mkdocs.yaml` configuration is I hope normal:
```
plugins:
  - i18n:
      docs_structure: suffix
      reconfigure_material: true
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: fr
          name: Français
          build: !ENV [FRENCH,true]
          site_name: 'Online Help (FR)'
```

And am deploying to mike using (there is no special mike configuration set):

```
mike deploy --push --update-aliases 4.2.5 latest 
```
