### ISSUE TITLE
"Help to translate" options in the language switcher

### ISSUE THREAD

**Issue by Andygol** [ultrabug/mkdocs-static-i18n#266]
I am attempting to replicate the following approach to encourage users to participate in the translation of a project based on Materials for MkDocs. This involves placing a call to action in the language menu drop-down, similar to what is done on the https://spaceship-prompt.sh website.

<img width="500" alt="image" src="https://github.com/ultrabug/mkdocs-static-i18n/assets/369696/3f929130-b556-4496-a222-6e110af2d38d">

In the **spaceship-prompt** repo I found next [code](https://github.com/spaceship-prompt/spaceship-prompt/blob/d2a301c00a5668cfa020ef4fd4017f7816f1c124/mkdocs.yml#L149-L168l)

```yaml
extra:
  alternate:
    - name: English
      lang: en
      link: .
    - name: Deutsch
      lang: de
      link: /de/
    - name: Français
      lang: fr
      link: /fr/
    - name: Українська
      lang: uk
      link: /uk/
    - name: 简体中文
      lang: zh
      link: /zh/
    - name: Help translating
      lang: null
      link: https://translate.spaceship-prompt.sh/
```

I would prefer not to use `alternate` but leverage the capabilities of **mkdocs-static-i18n** for implementing the language switcher.

```yml
plugin:
    - i18n:
      docs_structure: folder
      reconfigure_material: true
      languages:
        - locale: en
          name: English
        - locale: de
          name: Deutsch
        - locale: null
          name: Help to translate
          link: http://translate.service/
```

Unfortunately, I got next 
```log
ERROR   -  Config value 'plugins': Plugin 'i18n' option 'languages': Sub-option 'locale': Required configuration not provided.
Aborted with 1 configuration errors!
```

Even if I specified valid locale ISO-code, `link` is still invalid
```log
ERROR   -  Config value 'plugins': Plugin 'i18n' option 'languages': Sub-option 'link': languages[io].link should be an absolute
           link starting with a leading / and ending with a / (like /io/).
Aborted with 1 configuration errors!
```

Could you consider adding such a call to action option to facilitate translation efforts?
