### ISSUE TITLE
[Feature] Option to insert/inject content for fallback lang pages.

### ISSUE THREAD

**Issue by Andre601** [ultrabug/mkdocs-static-i18n#276]
I'm in the process of implementing multiple languages into my docs using this plugin.

For various reasons can I not translate all pages tho (i.e. auto-generated ones from code or other source files).
I still want to display them, so I use the fallback option for this.

With all that said, do I still want to display text, informing the user about the page not being translated.
But I also don't want them to copy over the page only to add that notice.

So I now want to suggest an option/way to allow inserting text into a fallback page.

One way I could think of is to add a jinja2 variable to use like `is_fallback`.
This would allow to create template overrides to display text if the page is a fallback.

Tho, then again the issue appears on how this text could be translated... 😅 
Maybe someone here has an idea?

**Comment by kamilkrzyskow** [comment]
The plugin already provides two context variables that would allow you to find out whether or not `is_fallback` is True:
https://ultrabug.github.io/mkdocs-static-i18n/setup/using-i18n-context/

In our docs we do exactly that, and insert a text to the announce bar with overrides. The text prompt is input manually into the Jinja2 syntax.

https://github.com/Gothic-Modding-Community/gmc/blob/dev/overrides/main.html#L35
https://gothic-modding-community.github.io/gmc/pl/zengin/worlds/

You could also place the call to action translation prompts in `extra` of mkdocs.yml and overwrite it for each language and refer to those in the Jinja2 syntax.

**Comment by Andre601** [comment]
Okay, thanks for the info. Tho, I'm a bit confused on your last sentence... What do you mean exactly with overwriting it?

I would like to use that extra aproach, as it avoid translators having to edit template files, but I'm not sure how I would implement this within jinja templating...

I know I can use a `{% set something = config.extra.path.to.something %}`, but how could I alter it to use a language option or smth?

**Comment by Andre601** [comment]
Also, another issue I face is the fact that some pages are not translatable, while others just aren't translated yet...

So I would need to find some way to display a different text based on if the page in question is not translated yet, or cannot be translated... But the only way I could think of is making a page with frontmatter to check, which would cause the file check thing to fail...

**Comment by Andre601** [comment]
Also, as a final note am I facing an issue I had in the past with another site, which is that the announce block is always visible in my docks, even when they are not used (Don't have a content).

And since blocks are apparently handled before if checks can I not wrap it into an if to not include while the page is not the default and non-existant...

**Comment by kamilkrzyskow** [comment]
> What do you mean exactly with overwriting it?

The overwrite method can be seen here:
https://ultrabug.github.io/mkdocs-static-i18n/setup/setting-up-languages/#additional-per-language-overrides-options
it was also bugged a while back with `extra`, but should be working now:
https://github.com/ultrabug/mkdocs-static-i18n/issues/267

Basically a short example of `mkdocs.yml` similar to our current override:
```yml
extra:
  announcement: 'This page has not yet been translated into LANGUAGE, therefore it is displayed in English.'
  # Announcement for the default English language
    
plugins:
  - i18n:
    languages:
      - locale: en
        default: true
        name: English
        build: true
      - locale: pl
        name: Polish
        build: true
        extra:
           announcement: 'Ta strona nie została jeszcze przetłumaczona na język polski, dlatego wyświetla się po angielsku.'
           # Overwrite the value on language switch
```

and then you use `{{ config.extra.announcement }}` in the Jinja2 template to access the value.

--- 

> another issue I face is the fact that some pages are not translatable,

Like you said, I agree you'd need to add a front-matter value for the pages that are not translatable.
You can then combine the conditional, modifying the example of our overrides:
`if i18n_page_locale != "en" and i18n_file_locale != i18n_page_locale and not page.meta.not_translatable`
There might be an issue with `page.meta` not being defined for the 404 template page, I'm not sure if that was fixed in MkDocs 1.5.0, if that happens you can add yet another condition:
`if page.meta and i18n_page_locale != "en" and i18n_file_locale != i18n_page_locale and not page.meta.not_translatable`

---

> Also, as a final note am I facing an issue I had in the past with another site, which is that the announce block is always visible in my docks, even when they are not used (Don't have a content).

Yes, and it was me that argued at some point that you did something incorrectly, but the time has come for me to apologize for that time.

Material for MkDocs has a somewhat _nasty_ condition in the `base.html`
https://github.com/squidfunk/mkdocs-material/blob/dfa5f0313893ff7fc254a8d74421735d5f1d3eb1/material/templates/base.html#L114
`if self.announce()`

In other words, if your `main.html` contains a `block announce` override it triggers that conditional and it adds the announcement bar wrapper `<aside class="md-banner">`, no matter if there is any content in your announce override.

It turned out I had the same issue, but I simply didn't want to fight for a nice, perhaps best solution, and I just added extra CSS to remove additional margin and keep the announce bar "hidden". 
https://github.com/Gothic-Modding-Community/gmc/blob/287e4bfe2daec82b237983252903a2d020bbf620/overrides/assets/stylesheets/extra.css#L205

In the override you can also notice that we have our own 
`<div class="gmc-announce">` to style it however we see fit.

**Comment by Andre601** [comment]
> The overwrite method can be seen here:
> https://ultrabug.github.io/mkdocs-static-i18n/setup/setting-up-languages/#additional-per-language-overrides-options
> it was also bugged a while back with `extra`, but should be working now:
> #267

From my testing it doesn't.

The announce block:
```
{% block announce %}
  {% if page.meta and i18n_page_locale != "en" and i18n_file_locale != i18n_page_locale %}
    <div class="announcement__translation">
      {% if page.meta.not_translatable %}
        {{ config.extra.not_translatable | d('This page cannot be translated and is therefore only available in English.') }}
      {% else %}
        {{ config.extra.missing_translation | d('This page has not yet been translated.') }}
      {% endif%}
    </div>
  {% endif %}
{% endblock %}
```

The mkdocs.yml content:
```
extra:
  social:
    - icon: 'simple/patreon'
      link: 'https://patreon.com/andre_601'
    - icon: 'simple/github'
      link: 'https://github.com/purrbot-site'
    - icon: 'simple/twitter'
      link: 'https://twitter.com/TruePurrBot'
    - icon: 'simple/mastodon'
      link: 'https://botsin.space/@purrbot'
  missing_translation: 'This page has not yet been translated.'
  not_translatable: 'This page cannot be translated and is therefore only available in English.'

plugins:
  - search
  - neoteroi.mkdocsoad:
      use_pymdownx: true
  - i18n:
      docs_structure: folder
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: de
          name: Deutsch
          build: true
          extra:
            missing_translation: 'Diese Seite wurde noch nicht übersetzt.'
            not_translatable: 'Diese Seite kann nicht übersetzt werden und ist darum nur auf Englisch verfügbar.'
          nav_translations:
            # Welcome system
            Welcome-System: Willkommenssystem
            # Contributing
            Contributing: Mitmachen
            Translations: Übersetzungen
            # Legal
            Legal: Rechtliches
```
