### ISSUE TITLE
Both languages show on the left-side menu instead of the current language's content only

### ISSUE THREAD

**Issue by ztheory** [ultrabug/mkdocs-static-i18n#289]
Hello,

Firstly, thank you for maintaining this project.

Running mkdocs-material 9.4.7 with mkdocs-static-i18n 1.2.0.

I am probably missing something simple, but I cannot figure it out.

When running `mkdocs serve`, I get the following warning, even though I have an `index.md` file in my /fr/ folder. Perhaps related to the second issue.

```
INFO    -  mkdocs_static_i18n: Building 'fr' documentation to directory: /tmp/mkdocs_8oc6466d/fr
WARNING -  mkdocs_static_i18n: Could not find a homepage for locale 'fr'
```

In addition, on the left menu, all of the content shows for both English and French, even when being in my /fr/ or /en/ version of the documentation.

Appreciate any advice in advance.

```
site_name: Quad9 Documentation
site_url: https://quad9dns.github.io/documentation/en
  #repo_url: https://github.com/Quad9DNS/documentation

plugins:
  - social:
      cards_layout_options:
        background_color: "#2E303E"
  - search
  - i18n:
      reconfigure_material: true
      fallback_to_default: false
      docs_structure: suffix
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: fr
          name: Français
          build: true
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
     alternate_style: true

extra_css:
  - stylesheets/extra.css

theme:
  name: material
  favicon: images/favicon.svg
  logo: assets/logo_light.svg
  font: false
  features:
    - navigation.index
    - navigation.sections
      #    - navigation.instant
    - toc.integrate
    - content.code.copy
    - header.autohide
  language: en
  palette:
    - scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to Light Mode
      primary: pink
      accent: pink
    - scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to Dark Mode
      primary: pink
      accent: pink

extra:
  alternate:
    - name: English
      link: /documentation/en/ 
      lang: en
    - name: Français
      link: /documentation/fr/
      lang: fr
```

![image](https://github.com/ultrabug/mkdocs-static-i18n/assets/1864677/3cb285a6-d761-44af-88d7-e961d243cffe)
