### ISSUE TITLE
Custom language selector (non-mkdocs-material)

### ISSUE THREAD

**Issue by tombreit** [ultrabug/mkdocs-static-i18n#297]
I would like to build a language selector in a custom (non-mkdocs-material) theme, but I do not know how to access the alternate language versions of a given page:

```html
<!-- theme/base.html -->

i18n_page_locale: {{ i18n_page_locale }} 
i18n_languages:    {{ i18n_languages }}
```
 ` i18n_page_locale` gives me the expected language code for the current language version.

But the variable `'i18n_languages' seem to be undefined.

How do I access the alternate language versions of a given page in a custom template?

**Comment by tombreit** [comment]
Hi @ultrabug, thanks for your prompt reply and the sitemap-hint! But in my case, there must be something wrong with my project setup - even `i18n_alternates` is not defined:

```yaml
# mkdocs.yml

site_name: Testsite
strict: true
plugins:
  - i18n:
      docs_structure: suffix
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: de
          name: Deutsch
          build: true
theme:
  name: null
  custom_dir: 'theme/'
```

```sh
# project layout
.
├── docs
│   ├── page1.de.md
│   └── page1.en.md
├── mkdocs.yml
├── theme_csl
│   ├── base.html
│   ├── main.html
│   └── mkdocs_theme.yml
└── upload.sh
```

```html
<!-- theme/base.html -->

i18n_page_locale:  {{ i18n_page_locale }} 
i18n_languages:    {{ i18n_languages }}
i18n_alternates:   {{ i18n_alternates.items() }}
```

→ `mkdocs serve` →

```bash
  File "project/theme_csl/main.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "project/theme_csl/base.html", line 86, in top-level template code
    {{ i18n_alternates.items() }}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "project/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 485, in getattr
    return getattr(obj, attribute)
           ^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'i18n_alternates' is undefined
```

Do you have any other tips or ideas?
