### ISSUE TITLE
Not yet translated files in duplicated navigation entry

### ISSUE THREAD

**Issue by WizzardMaker** [ultrabug/mkdocs-static-i18n#300]
I'm currently building a documentation site and stumbled across this bug while migrating my translations.
The used docs_structure is folder and I'm using mkdocs-material.

Translation fallback files get sorted in a separate navigation entry with the same name:
![image](https://github.com/ultrabug/mkdocs-static-i18n/assets/7768485/5642cb60-fa28-4db7-a049-8b8dff843864)

Here, `S3/Mana and magic/Test` is supposed to be filed with all other entries in `S3/Mana and magic/` above.

This is my mkdocs.yml:
```yaml
site_name: Settlers United Documentation

docs_dir: '../docs/'
extra_css:
  - stylesheets/extra.css


theme:
  favicon: assets/favicon.webp
  logo: assets/favicon.webp
  features:
    - content.tooltips
    - announce.dismiss
    - search.suggest
    - search.highlight
  name: material
  palette:
    scheme: slate
    primary: black
    accent: deep orange

markdown_extensions:
  - attr_list
  - abbr
  - md_in_html
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true


plugins:
  - search
  - i18n:
      fallback_to_default: true
      reconfigure_material: true
      reconfigure_search: true
      docs_structure: folder
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: de
          name: Deutsch
          site_name: Settlers United Dokumentation
          build: true
```

The folder structure is as follows (truncated for only necessary parts)
```
config/
  mkdocs.yml
docs/
  assets/
  de/
    S3/
      mana-and-magic/
        area-of-effect.md
        basics.md
        cost-progression.md
        table-of-knowledge.md
  en/
    S3/
      mana-and-magic/
        area-of-effect.md
        basics.md
        cost-progression.md
        table-of-knowledge.md
        test.md
        
```

I don't know if I configured something wrong with this plugin or if mkdocs-material is breaking something
