### ISSUE TITLE
 Since mkdocs-materal 8.3.7 search does not work in browser if there is Vietnamese locale in i18n plugin

### ISSUE THREAD

**Issue by oneumyvakin** [ultrabug/mkdocs-static-i18n#313]
lunrjs has en issue https://github.com/olivernn/lunr.js/issues/324 when working in strict mode ("use strict";)
Since 8.3.7 "use strict"; added to the beginning of search bundle.
This lead to the issue search in blower doesn't work because of JS error

search.07f07601.min.js:8 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'console')
at Object.warn (search.07f07601.min.js:8:61)
at t.Pipeline.warnIfFunctionNotRegistered (search.07f07601.min.js:17:393)
at t.Pipeline. (search.07f07601.min.js:18:319)
at Array.forEach ()
at t.Pipeline.add (search.07f07601.min.js:18:288)
at t.Builder. (lunr.multi.min.js:1:686)
at t.Builder.use (search.07f07601.min.js:40:3184)
at t.Builder. (search.07f07601.min.js:40:17975)
at t (index.ts:192:2)
at new H (search.07f07601.min.js:40:17829)

This issue happened only if Vietnamese locale exists in i18n plugin.

mkdocs-materal author think that this is the issue in i18n plugin: https://github.com/squidfunk/mkdocs-material/issues/7498

Steps to reproduce

1. Define mkdocs:
```
site_name: My Docs

theme:
  name: material

plugins:
  - search
  - i18n:
        languages:
              - locale: vi
                name: Vietnamese
                default: true
                build: yes
                nav_translations:
                  test: Hướng
```

2.    mkdocs serve --dev-addr=0.0.0.0:8000
3.    Try to search something.
4.    Check browsers console.

**Comment by ultrabug** [comment]
Hi

Well I'm sorry but unless I'm mistaken I will have to disagree with @squidfunk here.

If I remove the i18n plugin and set the material theme language to `vi` I can reproduce the console error `TypeError: e is undefined`.

```yaml
site_name: My Docs

theme:
  name: material
  language: vi

plugins:
  - search
```

So this looks to me that it is indeed a lunr.js problem affecting material as well?
