### ISSUE TITLE
Multiple Language File Handling in mkdocs-static-i18n

### ISSUE THREAD

**Issue by bimdoer** [ultrabug/mkdocs-static-i18n#321]
We're encountering an issue with the mkdocs-static-i18n plugin (version 1.3.0) regarding how it handles files with and without language suffixes.

**Expected Behavior:**
1. Files with language suffixes (e.g., file.de.md, file.en.md, file.fr.md, file.it.md) should only appear in their respective language versions of the site.
2. Files without language suffixes (e.g., file.md) should appear in all language versions of the site.

**Current Behavior:**
- With fallback_to_default: false: Language-specific files correctly stay in their respective languages, but regular .md files don't appear in any language version (only in the default language).
- With fallback_to_default: true: Regular .md files appear in all languages, but all .de.md files (our default language) also appear in every language version.
> The same problem exists with the pictures too. Some pictures are useful for all languages and we don't want to copy them for each language.

mkdocs.yml
```
plugins:
  - i18n:
      docs_structure: suffix
      fallback_to_default: false
      languages:
        - locale: de
          default: true
          name: Deutsch
          build: true
        - locale: fr
          name: Français
          build: true
        - locale: it
          name: Italiano
          build: true
        - locale: en
          name: English
          build: true
```

We've tried various combinations of these settings without success.
**Questions:**
1. Is there a way to make regular .md files appear in all languages while keeping language-specific files in their respective languages (same with referenced pictures)?
2. Is this a limitation of the current implementation or could this be addressed in a future release?
3. Are there any workarounds or alternative approaches to achieve this behavior?

**Environment:**
mkdocs-static-i18n: 1.3.0
MkDocs: [1.6.1]
Python: 3.12
OS: Windows
