### ISSUE TITLE
[Bug] html `lang` attribute not changing on language switch

### ISSUE THREAD

**Issue by Stanzilla** [ultrabug/mkdocs-static-i18n#39]
Example page: https://docs.coregames.com/

Steps: 
- Go to above website, inspect and check HTML's `lang` tag value. It should be `en`.
- Use the language switcher and switch to Francais (Beta). `lang` stays at `en`.

Config: 

```yml
  - i18n:
      default_language: en
      languages:
        fr: Français (Beta)
```

It works on https://ultrabug.github.io/mkdocs-static-i18n/ so I'm suspecting some config.
