### ISSUE TITLE
Bug with external links in tabs navigation

### ISSUE THREAD

**Issue by Stanzilla** [ultrabug/mkdocs-static-i18n#43]
Hello, it's me again! 👋

So on this example page: https://docs.coregames.com/fr/api/key_bindings/

If you look at the link "Core Academy" you can see that is missing a slash after the `https`

`<a href="https:/learn.coregames.com" class="md-tabs__link"> Core Academy </a>` same with other external links.

They are specified in the yaml as follows:

```yml
  - Core Academy:
      - Academy: https://learn.coregames.com
  - Forums:
      - Forums: https://forums.coregames.com
  - News:
      - News: https://forums.coregames.com/c/community/5
``` 

The links are fine on the non-/fr/ version
