### ISSUE TITLE
Switching between template files inside custom_dir for different languages

### ISSUE THREAD

**Issue by Kanaduchi** [ultrabug/mkdocs-static-i18n#49]
I have a case when in custom_dir of mkdocs theme I have some overrides of template html files (main.html, home.html):
```
theme:
  name: material
  custom_dir: overrides
  favicon: assets/icon.png
...
```

Is it possible to add possibility of switching between template files inside this dir for different languages?

Content of custom_dir folder:
- overrides/
  |_ main.html
  |_ main.fr.html
