### ISSUE TITLE
shouldn't generate the default language folder

### ISSUE THREAD

**Issue by zimocode** [ultrabug/mkdocs-static-i18n#5]

**Comment by zimocode** [comment]
if the .yml like this:

``` yaml
plugins:
  - i18n:
      default_language: en
      languages:
        en: english
        fr: français
```
the default language folder `http://127.0.0.1:8000/en` is unnecessary just the `fr` is ok. OR , give an option ? like:

``` yaml
  - i18n:
      default_language: en
      default_language_bulid: false
      languages:
        en: english
        fr: français
```

maybe, don't set `to languanes` ?

``` yaml
  - i18n:
      default_language: en
      languages:
        fr: français
```

**Comment by ultrabug** [comment]
Hi @zimocode 

Oh I see, indeed now I understand what you want :+1: I'll add an option okay

You'll have that today

**Comment by ultrabug** [comment]
@zimocode thanks again. After thinking about it I find it easier just to build the languages listed in the `languages` map..

I have documented and tested the feature. Happy version 0.5 mate !

**Comment by jrappen** [comment]
This solution creates an issue where:

When following the instructions at <https://github.com/ultrabug/mkdocs-static-i18n#not-building-a-dedicated-version-for-the-default-language>, this leaves us **without** the possibility of giving `default_language` a custom label.

Or in other words, we cannot label the usual `en` selection with `English` appropriately.

**Comment by brospars** [comment]
Hello @jrappen Did you find a workaround ?

**Comment by jrappen** [comment]
> ... you can simply ...

@brospars You cannot. The default language has a different path, compare (for example):

- `./`
- `./en/`
- `./fr/`

and from my testing in October does not copy the settings from its subdir counterpart.

**Comment by jrappen** [comment]
@brospars Your approach doesn't set a `default_language`.

**Comment by ultrabug** [comment]
@jrappen since this has been asked for multiple times I guess I'm being stubborn on this one and should offer an option to tackle this.

There are two ways we could make this happen:

1. add a `default_language_alternate_name` option
2. introduce a `build_language_paths` option which would be a list of the locales we want a /version for; allowing users to keep on having the `languages` option set for **every** language and only select the languages they actually want a /version for

Which would you guys prefer ?

friendly ping to @Stanzilla , @AngryMane , @Andre_601 in case they care to share their pov

**Comment by Andre601** [comment]
not really interested tbh

**Comment by Stanzilla** [comment]
I don't think I quite understand what the question is

**Comment by ultrabug** [comment]
sorry @Stanzilla ; the question is about having an option to allow users who do not wish to have a /version of their default language to have a way to still set the name they want to display for it on their material language switcher (when using the default generation one, not setting it by hand)

**Comment by Stanzilla** [comment]
What would it display otherwise? Feels inconsistent if that was different?

**Comment by ultrabug** [comment]
> What would it display otherwise? Feels inconsistent if that was different?

it would display "en" instead of "English" if using a config like this where I want only /fr and not /en since my default / is en

```
  - i18n:
      default_language: !ENV [DEFAULT_LANGUAGE, "en"]
      default_language_only: !ENV [DEFAULT_LANGUAGE_ONLY, false]
      languages:
        fr: français
```

**Comment by ultrabug** [comment]
@jrappen I see you reacted with a confused emoj

I personally like @brospars' idea very much as it could provide a consistent way to add options to each language without adding yet other options...

I would stick with the usual alternate key names (name, link) and we could also extend it to allow users to select if they want to build this language or not as well.

The default version would simply be named `default` to reflect this too!

Ofc, we would make that backward compatible so that users wanting a simpler config format could still use it.

Example :

```yaml
  - i18n:
      default_language: en
      languages:
        default: 
          - name: english
          - link: ./
          - build: true
        fr: 
          - name: français
          - link: ./fr
          - build: true
        en: 
          - label : english
          - path: ./en
          - build: false
        de: deutsch # Backward compatibility
```
