### ISSUE TITLE
Displayable name for default language

### ISSUE THREAD

**Issue by Kanaduchi** [ultrabug/mkdocs-static-i18n#50]
Currently if we specify config like
```
  - i18n:
      default_language: fr
      languages:
        en: English
```
then nf the language selector we will see two items: fr and English

My suggestion is to add new variable `default_language_label: French` for displayable label in the selector for default language

As I got it right the fix is quite simple:
1. Introduce new variable in the config scheme
```
("default_language_name", Locale(str, required=False)),
```
2. Read it in the creation of language list
```
"name": self.config["languages"].get(
self.config["default_language_name"],
self.config["default_language"]
```

**Comment by ultrabug** [comment]
@Kanaduchi or you could set the `extra.alternate` config by hand like this

```
extra:
  alternate:
    - name: English
      link: ./en/
      lang: en
    - name: Français
      link: ./fr/
      lang: fr
```

I'm unsure adding a specific config for a edge case is worth it?
