### ISSUE TITLE
nav_translations do not work with awesome-pages

### ISSUE THREAD

**Issue by phasel74** [ultrabug/mkdocs-static-i18n#65]
The `mkdocs.yml`
```YAML
site_name: Test
nav:
  - Home: index.md
theme:
  name: material
plugins:
  - awesome-pages
  - i18n:
      default_language: en
      languages:
        en: English
        de: Deutsch        
      nav_translations:
        de:
          'Home': Startseite
```

with `index.md`
```Markdown
# Welcome!
```

and `index.de.md`
```Markdown
# Herzlich Willkommen!
```
gives the German website

![grafik](https://user-images.githubusercontent.com/48174934/140091752-727fc2c5-5fa9-442e-b01d-f7050c1dd20d.png)

When I remove awesome-pages I get the expected website

![grafik](https://user-images.githubusercontent.com/48174934/140092149-498c2311-6622-4dbc-b649-8656dea08a28.png)

Is this an issue of awesome-pages or of i18n?
