### ISSUE TITLE
Navbar tab labels not being translated

### ISSUE THREAD

**Issue by jrappen** [ultrabug/mkdocs-static-i18n#66]
Given the config:

```yaml
# unrelevant code ommited

theme:
  name: material
  features:
    - navigation.tabs

nav:
  - Section:
      - index.en.md
      - other-page.en.md

plugins:
  - i18n:
      nav_translations:
        Section: 'Whatever "section" is when translated to the other language'
```

labels in the navigation (bar) tabs at the top are not being translated.

<img width="656" alt="image" src="https://user-images.githubusercontent.com/8577450/140584468-7be3a613-dd13-4870-a991-5d35e70f38f1.png">

**Comment by ultrabug** [comment]
Ok this one is easier, you just forgot the language key under `nav_translations`. This is necessary to be able to add translation for every supported language (may be more than one)

You can fix this like this:

```
  - i18n:
      default_language: en
      default_language_only: false
      languages:
        en: English
        de: Deutsch
      nav_translations:
        de:
          Home: Startseite
          Recipes: Rezepte
```
