### ISSUE TITLE
Filenames containing dots not working

### ISSUE THREAD

**Issue by brospars** [ultrabug/mkdocs-static-i18n#79]
For this given `docs` structure and this config
```
docs
├── index.en.md
├── index.md
├── topic1
│   ├── 1.1.exemple.en.md
│   ├── 1.1.exemple.fr.md
│   ├── index.en.md
│   └── index.fr.md
```

```
plugins:
  - i18n:
      default_language: fr
      languages:
        fr: Français
        en: English
```
I always get the english version : 

http://127.0.0.1:8000/Topic1/1.1.exemple.html => english (not ok)
http://127.0.0.1:8000/fr/Topic1/1.1.exemple.html => english (not ok)
http://127.0.0.1:8000/en/Topic1/1.1.exemple.html => english (ok)
