### ISSUE TITLE
Translate site_name

### ISSUE THREAD

**Issue by brospars** [ultrabug/mkdocs-static-i18n#80]
Is there a way to translate the `site_name` parameter ?

A plugin parameter could be great : 

```yaml
site_name: Mon super site
plugins:
  - i18n:
      default_language: fr
      languages:
        fr: Français
        en: English
      site_name_translations:
        en: My awesome website
```
