### ISSUE TITLE
Navigation links not translated at the bottom of the page

### ISSUE THREAD

**Issue by ehguille** [ultrabug/mkdocs-static-i18n#88]
Sorry If I fail explaining this.

I'm working whith the last version of mkdocs material and also mkdocs static i18n. They work like a charm.

However, with the following configuration:

```bash
plugins:
  - i18n: # https://github.com/ultrabug/mkdocs-static-i18n
      default_language: es
      languages:
        en: English
        es: Español
      nav_translations:
        en:
          Hola: Hi
          Docencia: Teaching
          Cosas: Stuff
```` 

I've found that the bottom links are not translated:

![image](https://user-images.githubusercontent.com/55703981/152510239-2cfaf6f2-4b3c-4ada-97e3-e5acbdaed699.png)

While the navbar is:

![image](https://user-images.githubusercontent.com/55703981/152510293-801e28e7-124c-41a7-8542-bd4d29865f2f.png)

Thanks a lot ❤️

**Comment by ultrabug** [comment]
Hi @ehguille do you have an actual repository for me to test this? because I've done a simple test here and it works as expected.

```
.
├── docs
│   ├── index.en.md
│   ├── index.es.md
│   ├── too.en.md
│   └── too.es.md
└── mkdocs.yml
```

with

```
site_name: My Docs

theme:
  name: material
  font:
    text: Ubuntu
    code: Ubuntu Mono
  icon:
    logo: material/file-document-multiple
  palette:
    primary: blue

nav:
  - Hola: index.md
  - Cosas: too.md

plugins:
  - i18n: # https://github.com/ultrabug/mkdocs-static-i18n
      default_language: es
      languages:
        en: English
        es: Español
      nav_translations:
        en:
          Hola: Hi
          Docencia: Teaching
          Cosas: Stuff
```

Bottom links are translated okay
